/**
 * Canonical homepage section order — TechTivAI Final Developer Agenda #9.
 */
export const homepageSectionOrder = [
  {
    id: "hero",
    number: 1,
    title: "Hero — Discover What AI Can Do For Your Business",
    label: "Hero",
    built: true,
  },
  {
    id: "stack",
    number: 2,
    title: "Interactive AI Technology Stack",
    label: "AI Technology Stack",
    built: true,
  },
  {
    id: "workflow",
    number: 3,
    title: "Workflow Automation",
    label: "Workflow Automation",
    built: true,
  },
  {
    id: "assessment",
    number: 4,
    title: "AI Business Assessment",
    label: "AI Business Assessment",
    built: true,
  },
  {
    id: "consultant",
    number: 5,
    title: "AI Consultant",
    label: "AI Consultant",
    built: true,
  },
  {
    id: "agents",
    number: 6,
    title: "AI / Agentic Solutions",
    label: "AI / Agentic Solutions",
    built: true,
  },
  {
    id: "automation",
    number: 7,
    title: "AI Automation",
    label: "AI Automation",
    built: true,
  },
  {
    id: "web-app",
    number: 8,
    title: "AI-Powered Web & App Development",
    label: "Web & App Development",
    built: true,
  },
  {
    id: "how-it-works",
    number: 9,
    title: "How It Works",
    label: "How It Works",
    built: true,
  },
  {
    id: "blueprint",
    number: 10,
    title: "Blueprint Preview",
    label: "Blueprint Preview",
    built: true,
  },
  {
    id: "pricing",
    number: 11,
    title: "Pricing",
    label: "Pricing",
    built: true,
  },
  {
    id: "faq",
    number: 12,
    title: "FAQ",
    label: "FAQ",
    built: true,
  },
  {
    id: "contact",
    number: 13,
    title: "Final CTA",
    label: "Final CTA",
    built: true,
  },
] as const;
