import { prisma } from "../../lib/prisma.js";
import { PIPELINE_USE_STUBS } from "../stub.js";
import type { PipelineContext } from "../types.js";
import { logInsight, logStepStart } from "../context.js";
import { updateAnalysisStatus, writeRawSignal } from "../update-status.js";

function webAppBaseUrl(): string {
  const url =
    process.env.WEB_APP_URL?.trim() ||
    process.env.BETTER_AUTH_URL?.trim() ||
    process.env.NEXT_PUBLIC_APP_URL?.trim() ||
    "http://localhost:3000";
  return url.replace(/\/$/, "");
}

/**
 * Phase 9: mark PDF ready and point Proposal.pdfUrl at the authenticated
 * download route. Bytes are generated on demand by Next.js (pdf-lib).
 * R2 upload can replace this URL later without changing the dashboard CTA.
 */
export async function runPdfStep(ctx: PipelineContext): Promise<void> {
  await updateAnalysisStatus(ctx.analysisId, "GENERATING_PDF");
  await logStepStart(ctx, "pdf", "Preparing your downloadable transformation blueprint…");

  const pdfUrl = `${webAppBaseUrl()}/api/analysis/${ctx.analysisId}/pdf`;

  const proposal = await prisma.proposal.findUnique({
    where: { analysisId: ctx.analysisId },
    select: { id: true },
  });

  if (proposal) {
    await prisma.proposal.update({
      where: { analysisId: ctx.analysisId },
      data: {
        pdfUrl,
        status: "SENT",
      },
    });
  } else if (!PIPELINE_USE_STUBS) {
    throw new Error(
      `Proposal missing for analysis ${ctx.analysisId} — cannot attach PDF URL`,
    );
  }

  await writeRawSignal(ctx.analysisId, "pdf", {
    domain: ctx.domain,
    pdfUrl: proposal ? pdfUrl : null,
    storage: "web-on-demand",
    stub: PIPELINE_USE_STUBS,
    message: proposal
      ? "PDF URL attached — download generated by web API"
      : "No proposal row — skipped pdfUrl persist",
  });

  await logInsight(ctx, "Blueprint package assembled — results ready for review.");
}
