-- AlterTable
ALTER TABLE "provider_config" ALTER COLUMN "monthlyBudgetUSD" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "currentSpendUSD" SET DEFAULT 0,
ALTER COLUMN "currentSpendUSD" SET DATA TYPE DOUBLE PRECISION;
